const TEMPOACTIONS = {
    SET_MIN_TEMPO: "SET_MIN_TEMPO",
    SET_MAX_TEMPO: "SET_MAX_TEMPO",
    SET_CURRENT_TEMPO_MOD: "SET_CURRENT_TEMPO_MOD",
    SET_SPEED_MOD_MAP: "SET_SPEED_MOD_MAP",
    SET_SCROLL_SPEED_PREVIEW: "SET_SCROLL_SPEED_PREVIEW"
}

export default TEMPOACTIONS;